global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data' 
    static_configs:
      - targets: ['prometheus:9090'] 

  - job_name: 'express-data'
    static_configs:
      - targets: ['node:8000']
  
  - job_name: 'mysql-data' 
    static_configs:
      - targets: ['mysql-exporter:9104'] 

  - job_name: 'cadvisor-data' 
    static_configs:
      - targets: ['cadvisor:8080'] 
  
  - job_name: 'node-data'
    static_configs:
      - targets: ['node_exporter:9100']